### ISSUE TITLE
`ccomp` should be used instead of `obj` when the target is a finite verb

### ISSUE THREAD

**Issue by Valentin-D-Richard** [UniversalDependencies/UD_Hindi-HDTB#4]
I briefly looked at this corpus and something looked off to me about the use of `obj`. Disclaimer, I don't speak Hindi.

When a finite verb depends on another word, we should expect a clausal relation, like `ccomp`, `xcomp`, `csubj`, `acl` or `advcl`. See https://universaldependencies.org/u/overview/complex-syntax.html#subordination

I see that there are a lot of finite verbs governed by `obj` in HDTB (762 occurrences):
http://universal.grew.fr/?custom=6418627bd7d40

In other corpora (ex. GSD in other languages), it is quite rare (around 10 occurrences in total). It corresponds to reported segments, titles, parentheses or "nominalized" verbs (maybe like English gerundive). I doubt that this is the case for all these occurrences.

Even if this corpus is based on Pāṇinian grammar, I would suggest to stick to UD guidelines and replace most `obj` by `ccomp` or `xcomp` when the target is a finite verb.

**Comment by dan-zeman** [comment]
Thanks for the report. Fixed in c37e1e932221f8b80cde8b62e1523c8f0eba1604 for Hindi and in [f9c5db95f34dd2504edd67fda92a9177f5529f1a](https://github.com/UniversalDependencies/UD_Urdu-UDTB/commit/f9c5db95f34dd2504edd67fda92a9177f5529f1a) for Urdu. Only the dependents headed by finite verbs vere fixed, so this is probably not the end of the story – there may be cases where a clause is headed by a participle, which has a child node with finite auxiliary.
